### ISSUE TITLE
Improve IP details & Remove usage of error suppression operator

### ISSUE THREAD

**Issue by atymic** [jeremykenedy/laravel-blocker#10]
The request to get the IP details is very slow, I think we should consider caching it to speed up browsing of the admin panel.

It also seems that the error suppression operator is used a lot in the IP checker
https://github.com/jeremykenedy/laravel-blocker/blob/master/src/App/Traits/IpAddressDetails.php#L22

**Comment by jeremykenedy** [comment]
I would say to please provide a potential solution in the form of a PR please
