### ISSUE TITLE
PSR-4 issue

### ISSUE THREAD

**Issue by mariopro** [jeremykenedy/laravel-blocker#13]
Hi,

Just got the message after composer autoload:
`Deprecation Notice: Class jeremykenedy\LaravelBlocker\Database\Seeds\DefaultBlockedTypeTableSeeder located in ./vendor/jeremykenedy/laravel-blocker/src/database/seeds/DefaultBlockedTypeTableSeeder.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.`

**Comment by jeremykenedy** [comment]
This can probably be fixed automatically through configuring style-ci to enforce ps4 standards. I welcome a pr :)
