### ISSUE TITLE
How to disable this class when testing?

### ISSUE THREAD

**Issue by lapubell** [jeremykenedy/laravel-blocker#21]
This blocker is great for prod, but when writing integration tests some of the auto generated content provided by faker gets trapped in the blocker, while some makes it through. This makes for inconsistent test behavior, as a test will sometimes fail when nothing has changed.

Is there a way to turn this package off when the ENV is set to "testing" or some other flag?

**Comment by jeremykenedy** [comment]
Yep:

```
LARAVEL_BLOCKER_ENABLED=false
```

**Comment by lapubell** [comment]
rad. for anyone else running into this, add this to your phpunit.xml:

```
    <php>
        ...
        <env name="LARAVEL_BLOCKER_ENABLED" value="false" />
    </php>

```
