### ISSUE TITLE
Resources not correctly scoped

### ISSUE THREAD

**Issue by atymic** [jeremykenedy/laravel-blocker#9]
I noticed that a lot of the views this package publishes are not scoped correctly.

https://github.com/jeremykenedy/laravel-blocker/tree/master/src/resources/views

Might be worth fixing so as not to pollute the vendor view directory

**Comment by jeremykenedy** [comment]
Please provide a potential solution in the form of a PR please.

**Comment by atymic** [comment]
I actually noticed when removing the package from my application, sorry.

**Comment by jeremykenedy** [comment]
I do not know what you mean by scoped correctly. Publishing them is optional.

**Comment by atymic** [comment]
When you publish the views, a bunch of directories are added to your `resources/views/vendor` folder.

So, instead of being like this:
```
resources/views/vendor
   /laravelblocker
      /scripts
      /partial
   /othervendorviews
   /othervendor2views
```
it looks like
```
resources/views/vendor
   /laravelblocker
   /scripts
   /partial
   /othervendorviews
   /othervendor2views
```

The sub folders of views in this package are mixed with top level package folders

https://github.com/jeremykenedy/laravel-blocker/blob/master/src/LaravelBlockerServiceProvider.php#L108-L110

**Comment by atymic** [comment]
In this folder, everything should be in the vendor namespace:
https://github.com/jeremykenedy/laravel-blocker/tree/master/src/resources/views

Or the service provider should publish them into `'resources/views/vendor/'.$this->_packageTag` rather than `'resources/views/vendor/'`
